---
- name: Check if traefik release exists
  ansible.builtin.command:
    cmd: helm status traefik -n traefik
  register: traefik_status
  changed_when: false
  failed_when: false

- name: Flag installed
  ansible.builtin.set_fact:
    traefik_installed: "{{ traefik_status.rc == 0 }}"

- name: Setup traefik if not installed
  when: not traefik_installed
  block:
    - name: Add repo traefik helm
      ansible.builtin.shell: |
        helm repo add traefik https://traefik.github.io/charts

    - name: Update helm repositories
      ansible.builtin.shell: |
        helm repo update

    - name: Install traefik helm
      ansible.builtin.shell: |
        helm install traefik traefik/traefik --wait \
          --namespace traefik \
          --create-namespace \
          --set namespace=traefik \
          --set ingressRoute.dashboard.enabled=true \
          --set ingressRoute.dashboard.matchRule='PathPrefix(`/dashboard`) || PathPrefix(`/api`)' \
          --set ingressRoute.dashboard.entryPoints={traefik} \
          --set ingressRoute.dashboard.services[0].kind=TraefikService \
          --set ingressRoute.dashboard.services[0].name=api@internal \
          --set providers.kubernetesGateway.enabled=true \
          --set gateway.namespacePolicy=All

- name: Setup Traefik dashboard access
  when: traefik_installed
  delegate_to: localhost
  become: false
  block:
    - name: Create BasicAuth secret for Traefik dashboard
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dashboard-auth-secret
            namespace: traefik
          type: Opaque
          stringData:
            users: |
              admin:{{ traefik_dashboard_htpasswd_bcrypt }}

    - name: Middleware BasicAuth for Traefik dashboard (use secret)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: dashboard-auth
            namespace: traefik
          spec:
            basicAuth:
              secret: dashboard-auth-secret
              realm: "Traefik"
              removeHeader: true
              headerField: "X-WebAuth-User"

    - name: IngressRoute for Traefik dashboard (HTTP)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata: { name: traefik-dashboard-external, namespace: traefik }
          spec:
            entryPoints: [ web ]
            routes:
              - match:  "Host(`traefik.{{ k3s_dns_domain_name }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
                kind: Rule
                middlewares:
                  - name: dashboard-auth
                    namespace: traefik
                services:
                  - name: api@internal
                    kind: TraefikService